"""add onboarding tables

Revision ID: 16265eb51959
Revises: 41fc8c9bc894
Create Date: 2026-05-26 19:37:18.528291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '16265eb51959'
down_revision: Union[str, None] = '41fc8c9bc894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_conditions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_conditions_user_id'), ['user_id'], unique=False)

    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('foods', sa.JSON(), nullable=False),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('region', sa.String(length=32), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('last_bp_check', sa.Date(), nullable=True),
    sa.Column('bp_systolic', sa.Integer(), nullable=True),
    sa.Column('bp_diastolic', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_preferences_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_preferences_user_id'))

    op.drop_table('user_preferences')
    with op.batch_alter_table('user_conditions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_conditions_user_id'))

    op.drop_table('user_conditions')
    # ### end Alembic commands ###
