"""add phase 3 tables

Revision ID: b971e9aef8fd
Revises: 16265eb51959
Create Date: 2026-06-02 17:28:45.827072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b971e9aef8fd'
down_revision: Union[str, None] = '16265eb51959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('local_name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meal_type', sa.String(length=16), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('prep_minutes', sa.Integer(), nullable=False),
    sa.Column('cook_minutes', sa.Integer(), nullable=False),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Integer(), nullable=False),
    sa.Column('carbs_g', sa.Integer(), nullable=False),
    sa.Column('fat_g', sa.Integer(), nullable=False),
    sa.Column('sodium_mg', sa.Integer(), nullable=False),
    sa.Column('potassium_mg', sa.Integer(), nullable=False),
    sa.Column('portion', sa.String(length=200), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('condition_safety', sa.JSON(), nullable=False),
    sa.Column('cuisine_region', sa.String(length=32), nullable=True),
    sa.Column('is_seeded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipes_meal_type'), ['meal_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipes_slug'), ['slug'], unique=True)

    op.create_table('grocery_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('quantity', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('naira_kobo', sa.Integer(), nullable=False),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_start', 'slug', name='uq_grocery_user_week_slug')
    )
    with op.batch_alter_table('grocery_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grocery_items_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grocery_items_week_start'), ['week_start'], unique=False)

    op.create_table('meal_plan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=16), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', 'meal_type', name='uq_meal_plan_items_user_date_meal')
    )
    with op.batch_alter_table('meal_plan_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_plan_items_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_plan_items_user_id'), ['user_id'], unique=False)

    op.create_table('recipe_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('naira_kobo', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_ingredients_recipe_id'), ['recipe_id'], unique=False)

    op.create_table('recipe_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipe_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_steps_recipe_id'), ['recipe_id'], unique=False)

    op.create_table('scan_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_results_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_results_user_id'))

    op.drop_table('scan_results')
    with op.batch_alter_table('recipe_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_steps_recipe_id'))

    op.drop_table('recipe_steps')
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_ingredients_recipe_id'))

    op.drop_table('recipe_ingredients')
    with op.batch_alter_table('meal_plan_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_plan_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_meal_plan_items_date'))

    op.drop_table('meal_plan_items')
    with op.batch_alter_table('grocery_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grocery_items_week_start'))
        batch_op.drop_index(batch_op.f('ix_grocery_items_user_id'))

    op.drop_table('grocery_items')
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipes_slug'))
        batch_op.drop_index(batch_op.f('ix_recipes_meal_type'))

    op.drop_table('recipes')
    # ### end Alembic commands ###
