"""add phase 4 tables

Revision ID: 6807135affac
Revises: b971e9aef8fd
Create Date: 2026-06-03 07:37:36.509131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6807135affac'
down_revision: Union[str, None] = 'b971e9aef8fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caregiver_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('caregiver_id', sa.Integer(), nullable=True),
    sa.Column('invite_phone', sa.String(length=32), nullable=False),
    sa.Column('invite_relationship', sa.String(length=32), nullable=False),
    sa.Column('invite_method', sa.String(length=16), nullable=False),
    sa.Column('invite_token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['caregiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('caregiver_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_caregiver_relationships_caregiver_id'), ['caregiver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_caregiver_relationships_invite_token'), ['invite_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_caregiver_relationships_patient_id'), ['patient_id'], unique=False)

    op.create_table('health_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('metric_type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('value_secondary', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_metrics_metric_type'), ['metric_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_metrics_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_metrics_user_id'))
        batch_op.drop_index(batch_op.f('ix_health_metrics_metric_type'))

    op.drop_table('health_metrics')
    with op.batch_alter_table('caregiver_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_caregiver_relationships_patient_id'))
        batch_op.drop_index(batch_op.f('ix_caregiver_relationships_invite_token'))
        batch_op.drop_index(batch_op.f('ix_caregiver_relationships_caregiver_id'))

    op.drop_table('caregiver_relationships')
    # ### end Alembic commands ###
