"""h2 dietitian relationships + patient notes + meal edit annotation

Revision ID: 7ebfb17ddcd3
Revises: 946fae976537
Create Date: 2026-06-08 22:53:35.737214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7ebfb17ddcd3'
down_revision: Union[str, None] = '946fae976537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dietitian_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('dietitian_id', sa.Integer(), nullable=False),
    sa.Column('invite_email', sa.String(length=255), nullable=False),
    sa.Column('invite_token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dietitian_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dietitian_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dietitian_relationships_dietitian_id'), ['dietitian_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dietitian_relationships_invite_token'), ['invite_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_dietitian_relationships_patient_id'), ['patient_id'], unique=False)

    op.create_table('patient_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('dietitian_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dietitian_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_notes_dietitian_id'), ['dietitian_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_notes_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('meal_plan_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited_by_dietitian_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dietitian_note', sa.Text(), nullable=True))
        batch_op.create_foreign_key(
            "fk_meal_plan_items_edited_by_dietitian_id",
            "users",
            ["edited_by_dietitian_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_plan_items', schema=None) as batch_op:
        batch_op.drop_constraint("fk_meal_plan_items_edited_by_dietitian_id", type_="foreignkey")
        batch_op.drop_column('dietitian_note')
        batch_op.drop_column('edited_by_dietitian_id')

    with op.batch_alter_table('patient_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_notes_patient_id'))
        batch_op.drop_index(batch_op.f('ix_patient_notes_dietitian_id'))

    op.drop_table('patient_notes')
    with op.batch_alter_table('dietitian_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dietitian_relationships_patient_id'))
        batch_op.drop_index(batch_op.f('ix_dietitian_relationships_invite_token'))
        batch_op.drop_index(batch_op.f('ix_dietitian_relationships_dietitian_id'))

    op.drop_table('dietitian_relationships')
    # ### end Alembic commands ###
