"""h1 email otp + caregiver invite by email

Revision ID: 77a2dbc1d561
Revises: fb7bd4ac58f5
Create Date: 2026-06-07 12:34:16.564266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '77a2dbc1d561'
down_revision: Union[str, None] = 'fb7bd4ac58f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caregiver_relationships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_email', sa.String(length=255), nullable=False))
        batch_op.drop_column('invite_method')
        batch_op.drop_column('invite_phone')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caregiver_relationships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_phone', sa.VARCHAR(length=32), nullable=False))
        batch_op.add_column(sa.Column('invite_method', sa.VARCHAR(length=16), nullable=False))
        batch_op.drop_column('invite_email')

    # ### end Alembic commands ###
