"""h1 add pending otp columns to user

Revision ID: 946fae976537
Revises: 77a2dbc1d561
Create Date: 2026-06-07 12:34:59.043058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '946fae976537'
down_revision: Union[str, None] = '77a2dbc1d561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_otp_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('otp_sent_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('otp_sent_at')
        batch_op.drop_column('pending_otp_hash')

    # ### end Alembic commands ###
