"""Nigerian therapeutic recipe corpus — AUTO-GENERATED, do not edit by hand.

Source: data/nigerian_corpus/{food_database.xlsx, diet_guide.xlsx}
Regenerate: ./venv/bin/python -m scripts.import_nigerian_corpus
Generated: 2026-06-12  (84 recipes)

condition_safety maps a condition slug to "caution" or "avoid"; a missing
slug means "safe" (the read-time default). Ratings derive from the
Nigerian Multi-Morbidity Diet Guide plus a documented rule layer.
"""

from sqlalchemy import delete, select
from sqlalchemy.orm import Session

from app.models.meal_plan import MealPlanItem
from app.models.recipe import Recipe, RecipeIngredient, RecipeStep
from app.models.scan import ScanResult

RECIPES: list[dict] = [   {   'slug': 'tuwo-shinkafa',
        'name': 'Tuwo Shinkafa',
        'local_name': 'Rice Tuwo / Tuwon Shinkafa',
        'description': 'Soft sticky rice pudding rolled into balls; served with various soups',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/vegetable-soup.jpg',
        'portion': '1 serving',
        'reason': 'Soft sticky rice pudding rolled into balls',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 216,
        'protein': 5,
        'carbs': 39,
        'fat': 4,
        'sodium_mg': 60,
        'potassium_mg': 280,
        'region': 'north-west',
        'ethnic_origin': 'Hausa/Fulani',
        'condition_safety': {'diabetes': 'caution'},
        'ingredients': [   ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0),
                           ('Smoked fish', '1 portion', 'proteins', 0)],
        'steps': ['Soft sticky rice pudding rolled into balls.', 'Served with various soups.']},
    {   'slug': 'tuwo-masara',
        'name': 'Tuwo Masara',
        'local_name': 'Corn Tuwo / Tuwon Masara',
        'description': 'Thick porridge made from cornmeal/maize flour; eaten with soups',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/vegetable-soup.jpg',
        'portion': '1 serving',
        'reason': 'Thick porridge made from cornmeal/maize flour',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 450,
        'protein': 11,
        'carbs': 81,
        'fat': 9,
        'sodium_mg': 60,
        'potassium_mg': 280,
        'region': 'north-west',
        'ethnic_origin': 'Hausa',
        'condition_safety': {'diabetes': 'caution'},
        'ingredients': [   ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0),
                           ('Smoked fish', '1 portion', 'proteins', 0)],
        'steps': ['Thick porridge made from cornmeal/maize flour.', 'Eaten with soups.']},
    {   'slug': 'tuwon-dawa',
        'name': 'Tuwon Dawa',
        'local_name': 'Guinea Corn Tuwo',
        'description': 'Ground sorghum (guinea corn) cooked thick; served with miyan kuka',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/vegetable-soup.jpg',
        'portion': '1 serving',
        'reason': 'Ground sorghum (guinea corn) cooked thick',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 380,
        'protein': 10,
        'carbs': 68,
        'fat': 8,
        'sodium_mg': 60,
        'potassium_mg': 280,
        'region': 'north-west',
        'ethnic_origin': 'Hausa',
        'condition_safety': {'diabetes': 'caution'},
        'ingredients': [   ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0),
                           ('Smoked fish', '1 portion', 'proteins', 0)],
        'steps': ['Ground sorghum (guinea corn) cooked thick.', 'Served with miyan kuka.']},
    {   'slug': 'miyan-kuka',
        'name': 'Miyan Kuka',
        'local_name': 'Baobab Leaf Soup',
        'description': 'Thick green draw-soup made from ground baobab leaves, dried fish, spices',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/bitter-leaf-soup.jpg',
        'portion': '1 serving',
        'reason': 'Thick green draw-soup made from ground baobab leaves, dried fish, spices',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 150,
        'protein': 11,
        'carbs': 8,
        'fat': 8,
        'sodium_mg': 480,
        'potassium_mg': 520,
        'region': 'north-west',
        'ethnic_origin': 'Hausa/Fulani',
        'condition_safety': {'diabetes': 'caution'},
        'ingredients': [   ('Dried Fish', '1 portion', 'proteins', 0),
                           ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0)],
        'steps': [   'Thick green draw-soup made from ground baobab leaves, dried fish, spices.',
                     'Serve warm.']},
    {   'slug': 'miyan-taushe',
        'name': 'Miyan Taushe',
        'local_name': 'Pumpkin Soup',
        'description': 'Rich pumpkin-based soup with spinach, goat/mutton, smoked fish',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/vegetable-soup.jpg',
        'portion': '1 serving',
        'reason': 'Rich pumpkin-based soup with spinach, goat/mutton, smoked fish',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 200,
        'protein': 15,
        'carbs': 10,
        'fat': 11,
        'sodium_mg': 480,
        'potassium_mg': 520,
        'region': 'north-west',
        'ethnic_origin': 'Hausa',
        'condition_safety': {'diabetes': 'caution'},
        'ingredients': [   ('Pumpkin', '1 portion', 'vegetables', 0),
                           ('Spinach', '1 portion', 'vegetables', 0),
                           ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0)],
        'steps': [   'Rich pumpkin-based soup with spinach, goat/mutton, smoked fish.',
                     'Serve warm.']},
    {   'slug': 'danwake',
        'name': 'Danwake',
        'local_name': 'Bean Dumplings',
        'description': 'Cowpea flour shaped into dumplings and boiled; served with sauce',
        'meal_type': 'snack',
        'image': '/static/recipe-images/puff-puff.jpg',
        'portion': '1 serving',
        'reason': 'Cowpea flour shaped into dumplings and boiled',
        'prep': 15,
        'cook': 20,
        'servings': 1,
        'calories': 250,
        'protein': 11,
        'carbs': 34,
        'fat': 8,
        'sodium_mg': 200,
        'potassium_mg': 320,
        'region': 'north-west',
        'ethnic_origin': 'Hausa',
        'condition_safety': {},
        'ingredients': [   ('Groundnut oil', 'for frying', 'essentials', 0),
                           ('Salt', 'a pinch', 'essentials', 0)],
        'steps': ['Cowpea flour shaped into dumplings and boiled.', 'Served with sauce.']},
    {   'slug': 'kilishi',
        'name': 'Kilishi',
        'local_name': 'Dried Spiced Beef',
        'description': 'Sun-dried beef marinated in groundnut paste and spices',
        'meal_type': 'snack',
        'image': '/static/recipe-images/vegetable-rice-and-beef.jpg',
        'portion': '1 serving',
        'reason': 'Sun-dried beef marinated in groundnut paste and spices',
        'prep': 15,
        'cook': 20,
        'servings': 1,
        'calories': 400,
        'protein': 35,
        'carbs': 10,
        'fat': 24,
        'sodium_mg': 520,
        'potassium_mg': 360,
        'region': 'north-west',
        'ethnic_origin': 'Hausa',
        'condition_safety': {'hypertension': 'caution', 'uric-acid': 'caution'},
        'ingredients': [   ('Groundnut oil', 'for frying', 'essentials', 0),
                           ('Salt', 'a pinch', 'essentials', 0)],
        'steps': ['Sun-dried beef marinated in groundnut paste and spices.', 'Serve warm.']},
    {   'slug': 'fura-da-nono',
        'name': 'Fura Da Nono',
        'local_name': 'Millet Balls + Yoghurt',
        'description': 'Ground millet balls mixed with fermented cow milk (nono)',
        'meal_type': 'breakfast',
        'image': '/static/recipe-images/fura-da-nono.jpg',
        'portion': '1 serving',
        'reason': 'Ground millet balls mixed with fermented cow milk (nono)',
        'prep': 15,
        'cook': 20,
        'servings': 1,
        'calories': 250,
        'protein': 11,
        'carbs': 34,
        'fat': 8,
        'sodium_mg': 200,
        'potassium_mg': 320,
        'region': 'north-west',
        'ethnic_origin': 'Fulani',
        'condition_safety': {},
        'ingredients': [   ('Groundnut', '1 handful', 'proteins', 0),
                           ('Milk', 'to taste', 'essentials', 0)],
        'steps': ['Ground millet balls mixed with fermented cow milk (nono).', 'Serve warm.']},
    {   'slug': 'gurasa',
        'name': 'Gurasa',
        'local_name': 'Flatbread / Leavened Bread',
        'description': 'Soft leavened bread baked on a griddle; enjoyed with stew or alone',
        'meal_type': 'snack',
        'image': '/static/recipe-images/akara-and-bread.jpg',
        'portion': '1 serving',
        'reason': 'Soft leavened bread baked on a griddle',
        'prep': 15,
        'cook': 20,
        'servings': 1,
        'calories': 280,
        'protein': 7,
        'carbs': 50,
        'fat': 6,
        'sodium_mg': 60,
        'potassium_mg': 280,
        'region': 'north-west',
        'ethnic_origin': 'Hausa',
        'condition_safety': {},
        'ingredients': [   ('Groundnut oil', 'for frying', 'essentials', 0),
                           ('Salt', 'a pinch', 'essentials', 0)],
        'steps': ['Soft leavened bread baked on a griddle.', 'Enjoyed with stew or alone.']},
    {   'slug': 'kuli-kuli',
        'name': 'Kuli-Kuli',
        'local_name': 'Groundnut Cake',
        'description': 'Deep-fried groundnut paste formed into cakes/rings; crunchy snack',
        'meal_type': 'snack',
        'image': '/static/recipe-images/garri-with-milk-and-groundnut.jpg',
        'portion': '1 serving',
        'reason': 'Deep-fried groundnut paste formed into cakes/rings',
        'prep': 15,
        'cook': 20,
        'servings': 1,
        'calories': 500,
        'protein': 22,
        'carbs': 69,
        'fat': 15,
        'sodium_mg': 200,
        'potassium_mg': 320,
        'region': 'north-west',
        'ethnic_origin': 'Hausa',
        'condition_safety': {'weight': 'caution'},
        'ingredients': [   ('Groundnut oil', 'for frying', 'essentials', 0),
                           ('Salt', 'a pinch', 'essentials', 0)],
        'steps': ['Deep-fried groundnut paste formed into cakes/rings.', 'Crunchy snack.']},
    {   'slug': 'masa',
        'name': 'Masa',
        'local_name': 'Rice Cake / Pan Cake',
        'description': 'Fermented rice batter cooked in special molds; slightly sour',
        'meal_type': 'breakfast',
        'image': '/static/recipe-images/masa.jpg',
        'portion': '1 serving',
        'reason': 'Fermented rice batter cooked in special molds',
        'prep': 15,
        'cook': 20,
        'servings': 1,
        'calories': 200,
        'protein': 9,
        'carbs': 28,
        'fat': 6,
        'sodium_mg': 200,
        'potassium_mg': 320,
        'region': 'north-west',
        'ethnic_origin': 'Hausa',
        'condition_safety': {},
        'ingredients': [   ('Groundnut', '1 handful', 'proteins', 0),
                           ('Milk', 'to taste', 'essentials', 0)],
        'steps': ['Fermented rice batter cooked in special molds.', 'Slightly sour.']},
    {   'slug': 'funkaso',
        'name': 'Funkaso',
        'local_name': 'Millet Pancake',
        'description': 'Fermented millet batter fried into crispy pancakes',
        'meal_type': 'breakfast',
        'image': '/static/recipe-images/pap-and-milk.jpg',
        'portion': '1 serving',
        'reason': 'Fermented millet batter fried into crispy pancakes',
        'prep': 15,
        'cook': 20,
        'servings': 1,
        'calories': 180,
        'protein': 8,
        'carbs': 25,
        'fat': 5,
        'sodium_mg': 200,
        'potassium_mg': 320,
        'region': 'north-west',
        'ethnic_origin': 'Hausa',
        'condition_safety': {},
        'ingredients': [   ('Groundnut', '1 handful', 'proteins', 0),
                           ('Milk', 'to taste', 'essentials', 0)],
        'steps': ['Fermented millet batter fried into crispy pancakes.', 'Serve warm.']},
    {   'slug': 'suya-tsire-isire',
        'name': 'Suya / Tsire / Isire',
        'local_name': 'Spicy Grilled Meat',
        'description': 'Thin-sliced beef/ram/chicken skewered and grilled with suya spice blend',
        'meal_type': 'snack',
        'image': '/static/recipe-images/suya-alt.jpg',
        'portion': '1 serving',
        'reason': 'Thin-sliced beef/ram/chicken skewered and grilled with suya spice blend',
        'prep': 15,
        'cook': 20,
        'servings': 1,
        'calories': 250,
        'protein': 22,
        'carbs': 6,
        'fat': 15,
        'sodium_mg': 520,
        'potassium_mg': 360,
        'region': 'north-west',
        'ethnic_origin': 'Hausa',
        'condition_safety': {'hypertension': 'caution', 'uric-acid': 'caution'},
        'ingredients': [   ('Suya Spice', '1 portion', 'essentials', 0),
                           ('Groundnut oil', 'for frying', 'essentials', 0),
                           ('Salt', 'a pinch', 'essentials', 0)],
        'steps': [   'Thin-sliced beef/ram/chicken skewered and grilled with suya spice blend.',
                     'Serve warm.']},
    {   'slug': 'miyan-gyada',
        'name': 'Miyan Gyada',
        'local_name': 'Groundnut Soup',
        'description': 'Rich peanut-based thick soup with meat and spices',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/garri-with-milk-and-groundnut.jpg',
        'portion': '1 serving',
        'reason': 'Rich peanut-based thick soup with meat and spices',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 300,
        'protein': 22,
        'carbs': 15,
        'fat': 17,
        'sodium_mg': 480,
        'potassium_mg': 520,
        'region': 'north-west',
        'ethnic_origin': 'Hausa',
        'condition_safety': {'diabetes': 'caution'},
        'ingredients': [   ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0),
                           ('Smoked fish', '1 portion', 'proteins', 0)],
        'steps': ['Rich peanut-based thick soup with meat and spices.', 'Serve warm.']},
    {   'slug': 'miyan-wake',
        'name': 'Miyan Wake',
        'local_name': 'Bean Soup / Stew',
        'description': 'Black-eyed pea soup seasoned with potash and spices',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/vegetable-soup.jpg',
        'portion': '1 serving',
        'reason': 'Black-eyed pea soup seasoned with potash and spices',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 200,
        'protein': 15,
        'carbs': 10,
        'fat': 11,
        'sodium_mg': 480,
        'potassium_mg': 520,
        'region': 'north-west',
        'ethnic_origin': 'Hausa',
        'condition_safety': {'diabetes': 'caution'},
        'ingredients': [   ('Potash', '1 portion', 'essentials', 0),
                           ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0)],
        'steps': ['Black-eyed pea soup seasoned with potash and spices.', 'Serve warm.']},
    {   'slug': 'miyan-zogale',
        'name': 'Miyan Zogale',
        'local_name': 'Moringa Leaf Soup',
        'description': 'Nutritious soup made from moringa (zogale) leaves',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/bitter-leaf-soup.jpg',
        'portion': '1 serving',
        'reason': 'Nutritious soup made from moringa (zogale) leaves',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 80,
        'protein': 6,
        'carbs': 4,
        'fat': 4,
        'sodium_mg': 480,
        'potassium_mg': 520,
        'region': 'north-west',
        'ethnic_origin': 'Hausa',
        'condition_safety': {'diabetes': 'caution'},
        'ingredients': [   ('Moringa', '1 portion', 'vegetables', 0),
                           ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0)],
        'steps': ['Nutritious soup made from moringa (zogale) leaves.', 'Serve warm.']},
    {   'slug': 'alkubus',
        'name': 'Alkubus',
        'local_name': 'Steamed Bean Cake',
        'description': 'Steamed cake made from ground beans; similar to moi moi',
        'meal_type': 'snack',
        'image': '/static/recipe-images/puff-puff.jpg',
        'portion': '1 serving',
        'reason': 'Steamed cake made from ground beans',
        'prep': 15,
        'cook': 20,
        'servings': 1,
        'calories': 200,
        'protein': 9,
        'carbs': 28,
        'fat': 6,
        'sodium_mg': 200,
        'potassium_mg': 320,
        'region': 'north-west',
        'ethnic_origin': 'Hausa',
        'condition_safety': {},
        'ingredients': [   ('Groundnut oil', 'for frying', 'essentials', 0),
                           ('Salt', 'a pinch', 'essentials', 0)],
        'steps': ['Steamed cake made from ground beans.', 'Similar to moi moi.']},
    {   'slug': 'adha-acha-pottage',
        'name': 'Adha / Acha Pottage',
        'local_name': 'Hungry Rice Porridge',
        'description': 'Pottage made from acha (fonio) grain',
        'meal_type': 'lunch',
        'image': '/static/recipe-images/boiled-rice-and-beans-with-sauce.jpg',
        'portion': '1 serving',
        'reason': 'Pottage made from acha (fonio) grain',
        'prep': 20,
        'cook': 35,
        'servings': 1,
        'calories': 171,
        'protein': 4,
        'carbs': 31,
        'fat': 3,
        'sodium_mg': 60,
        'potassium_mg': 280,
        'region': 'north-west',
        'ethnic_origin': 'Hausa',
        'condition_safety': {},
        'ingredients': [   ('Onion', '1 medium', 'vegetables', 0),
                           ('Tomato', '2 medium', 'vegetables', 0),
                           ('Vegetable oil', '1 tbsp', 'essentials', 0)],
        'steps': ['Pottage made from acha (fonio) grain.', 'Serve warm.']},
    {   'slug': 'burabisco',
        'name': 'Burabisco',
        'local_name': 'Northern Couscous',
        'description': 'Traditionally made couscous paired with spicy meat and vegetable stew',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/vegetable-soup.jpg',
        'portion': '1 serving',
        'reason': 'Traditionally made couscous paired with spicy meat and vegetable stew',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 220,
        'protein': 6,
        'carbs': 40,
        'fat': 4,
        'sodium_mg': 60,
        'potassium_mg': 280,
        'region': 'north-east',
        'ethnic_origin': 'Kanuri',
        'condition_safety': {},
        'ingredients': [   ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0),
                           ('Smoked fish', '1 portion', 'proteins', 0)],
        'steps': [   'Traditionally made couscous paired with spicy meat and vegetable stew.',
                     'Serve warm.']},
    {   'slug': 'nkwobi-kannuri-style',
        'name': 'Nkwobi (Kannuri Style)',
        'local_name': 'Spiced Cow Foot',
        'description': 'Spiced offal and cow feet; popular in Adamawa celebrations',
        'meal_type': 'snack',
        'image': '/static/recipe-images/peppered-kpomo.jpg',
        'portion': '1 serving',
        'reason': 'Spiced offal and cow feet',
        'prep': 15,
        'cook': 20,
        'servings': 1,
        'calories': 350,
        'protein': 16,
        'carbs': 48,
        'fat': 10,
        'sodium_mg': 200,
        'potassium_mg': 320,
        'region': 'north-east',
        'ethnic_origin': 'Fulani / Northern',
        'condition_safety': {'heart': 'avoid', 'cholesterol': 'avoid', 'uric-acid': 'avoid'},
        'ingredients': [   ('Groundnut oil', 'for frying', 'essentials', 0),
                           ('Salt', 'a pinch', 'essentials', 0)],
        'steps': ['Spiced offal and cow feet.', 'Popular in Adamawa celebrations.']},
    {   'slug': 'miyan-kubewa',
        'name': 'Miyan Kubewa',
        'local_name': 'Okra Soup',
        'description': 'Okra cooked into a slimy soup with assorted meats and fish',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/seafood-okra-soup.jpg',
        'portion': '1 serving',
        'reason': 'Okra cooked into a slimy soup with assorted meats and fish',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 120,
        'protein': 9,
        'carbs': 6,
        'fat': 7,
        'sodium_mg': 480,
        'potassium_mg': 520,
        'region': 'north-east',
        'ethnic_origin': 'Hausa/Fulani',
        'condition_safety': {'diabetes': 'caution'},
        'ingredients': [   ('Okra', '1 portion', 'vegetables', 0),
                           ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0)],
        'steps': ['Okra cooked into a slimy soup with assorted meats and fish.', 'Serve warm.']},
    {   'slug': 'kunu',
        'name': 'Kunu',
        'local_name': 'Millet Drink / Porridge',
        'description': 'Fermented millet or guinea corn porridge drink',
        'meal_type': 'breakfast',
        'image': '/static/recipe-images/pap-and-milk.jpg',
        'portion': '1 serving',
        'reason': 'Fermented millet or guinea corn porridge drink',
        'prep': 15,
        'cook': 20,
        'servings': 1,
        'calories': 150,
        'protein': 7,
        'carbs': 21,
        'fat': 4,
        'sodium_mg': 200,
        'potassium_mg': 320,
        'region': 'north-east',
        'ethnic_origin': 'Hausa/Kanuri',
        'condition_safety': {},
        'ingredients': [   ('Groundnut', '1 handful', 'proteins', 0),
                           ('Milk', 'to taste', 'essentials', 0)],
        'steps': ['Fermented millet or guinea corn porridge drink.', 'Serve warm.']},
    {   'slug': 'pate',
        'name': 'Pate',
        'local_name': 'Ground Corn Porridge',
        'description': 'Corn or rice porridge with vegetables, tomatoes, garden eggs, locust beans',
        'meal_type': 'lunch',
        'image': '/static/recipe-images/boiled-rice-and-beans-with-sauce.jpg',
        'portion': '1 serving',
        'reason': 'Corn or rice porridge with vegetables, tomatoes, garden eggs, locust beans',
        'prep': 20,
        'cook': 35,
        'servings': 1,
        'calories': 280,
        'protein': 7,
        'carbs': 50,
        'fat': 6,
        'sodium_mg': 60,
        'potassium_mg': 280,
        'region': 'north-east',
        'ethnic_origin': 'Hausa/Plateau Tribes',
        'condition_safety': {},
        'ingredients': [   ('Tomatoes', '1 portion', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0),
                           ('Tomato', '2 medium', 'vegetables', 0),
                           ('Vegetable oil', '1 tbsp', 'essentials', 0)],
        'steps': [   'Corn or rice porridge with vegetables, tomatoes, garden eggs, locust beans.',
                     'Serve warm.']},
    {   'slug': 'amiedi-nupe',
        'name': 'Amiedi (Nupe)',
        'local_name': 'Pounded Yam with groundnut soup',
        'description': 'Pounded yam served with a groundnut-based soup; Nupe delicacy',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/garri-with-milk-and-groundnut.jpg',
        'portion': '1 serving',
        'reason': 'Pounded yam served with a groundnut-based soup',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 700,
        'protein': 18,
        'carbs': 126,
        'fat': 14,
        'sodium_mg': 60,
        'potassium_mg': 280,
        'region': 'north-central',
        'ethnic_origin': 'Nupe',
        'condition_safety': {'weight': 'avoid'},
        'ingredients': [   ('Yam', '1 portion', 'vegetables', 0),
                           ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0)],
        'steps': ['Pounded yam served with a groundnut-based soup.', 'Nupe delicacy.']},
    {   'slug': 'egwusi-omi-benue',
        'name': 'Egwusi Omi (Benue)',
        'local_name': 'Egusi Soup',
        'description': 'Thick egusi (melon seed) soup cooked with vegetables and assorted meats',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/vegetable-soup.jpg',
        'portion': '1 serving',
        'reason': 'Thick egusi (melon seed) soup cooked with vegetables and assorted meats',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 400,
        'protein': 30,
        'carbs': 20,
        'fat': 22,
        'sodium_mg': 480,
        'potassium_mg': 520,
        'region': 'north-central',
        'ethnic_origin': 'Tiv / Idoma',
        'condition_safety': {},
        'ingredients': [   ('Egusi', '1 portion', 'essentials', 0),
                           ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0)],
        'steps': [   'Thick egusi (melon seed) soup cooked with vegetables and assorted meats.',
                     'Serve warm.']},
    {   'slug': 'acha-pottage',
        'name': 'Acha Pottage',
        'local_name': 'Fonio Porridge',
        'description': 'Cooked fonio grain; highly nutritious ancient grain dish',
        'meal_type': 'lunch',
        'image': '/static/recipe-images/boiled-rice-and-beans-with-sauce.jpg',
        'portion': '1 serving',
        'reason': 'Cooked fonio grain',
        'prep': 20,
        'cook': 35,
        'servings': 1,
        'calories': 171,
        'protein': 4,
        'carbs': 31,
        'fat': 3,
        'sodium_mg': 60,
        'potassium_mg': 280,
        'region': 'north-central',
        'ethnic_origin': 'Plateau tribes (Birom/Anaguta)',
        'condition_safety': {},
        'ingredients': [   ('Onion', '1 medium', 'vegetables', 0),
                           ('Tomato', '2 medium', 'vegetables', 0),
                           ('Vegetable oil', '1 tbsp', 'essentials', 0)],
        'steps': ['Cooked fonio grain.', 'Highly nutritious ancient grain dish.']},
    {   'slug': 'tiv-sesame-soup-nzogbu',
        'name': 'Tiv Sesame Soup (Nzogbu)',
        'local_name': 'Sesame Seed Soup',
        'description': 'Unique sesame paste-based soup; Tiv staple',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/vegetable-soup.jpg',
        'portion': '1 serving',
        'reason': 'Unique sesame paste-based soup',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 250,
        'protein': 19,
        'carbs': 12,
        'fat': 14,
        'sodium_mg': 480,
        'potassium_mg': 520,
        'region': 'north-central',
        'ethnic_origin': 'Tiv',
        'condition_safety': {},
        'ingredients': [   ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0),
                           ('Smoked fish', '1 portion', 'proteins', 0)],
        'steps': ['Unique sesame paste-based soup.', 'Tiv staple.']},
    {   'slug': 'gwate',
        'name': 'Gwate',
        'local_name': 'Locust Bean Soup',
        'description': 'Rich soup made from fermented locust beans (dawadawa)',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/vegetable-soup.jpg',
        'portion': '1 serving',
        'reason': 'Rich soup made from fermented locust beans (dawadawa)',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 180,
        'protein': 14,
        'carbs': 9,
        'fat': 10,
        'sodium_mg': 480,
        'potassium_mg': 520,
        'region': 'north-central',
        'ethnic_origin': 'Tiv / Alago',
        'condition_safety': {},
        'ingredients': [   ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0),
                           ('Smoked fish', '1 portion', 'proteins', 0)],
        'steps': ['Rich soup made from fermented locust beans (dawadawa).', 'Serve warm.']},
    {   'slug': 'okra-soup-north-central',
        'name': 'Okra Soup (North Central)',
        'local_name': 'Draw Soup / Ogbono Mix',
        'description': 'Slippery okra soup; widely consumed across the Middle Belt',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/seafood-okra-soup.jpg',
        'portion': '1 serving',
        'reason': 'Slippery okra soup',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 120,
        'protein': 9,
        'carbs': 6,
        'fat': 7,
        'sodium_mg': 480,
        'potassium_mg': 520,
        'region': 'north-central',
        'ethnic_origin': 'Various',
        'condition_safety': {},
        'ingredients': [   ('Okra', '1 portion', 'vegetables', 0),
                           ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0)],
        'steps': ['Slippery okra soup.', 'Widely consumed across the Middle Belt.']},
    {   'slug': 'pounded-yam-north-central',
        'name': 'Pounded Yam (North Central)',
        'local_name': 'Iyan / Utara',
        'description': "Pounded yam made from fresh white yam; Benue is Nigeria's yam capital",
        'meal_type': 'dinner',
        'image': '/static/recipe-images/amala-and-vegetable-soup.jpg',
        'portion': '1 serving',
        'reason': 'Pounded yam made from fresh white yam',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 400,
        'protein': 10,
        'carbs': 72,
        'fat': 8,
        'sodium_mg': 60,
        'potassium_mg': 280,
        'region': 'north-central',
        'ethnic_origin': 'Tiv / Nupe / Igala',
        'condition_safety': {'diabetes': 'caution', 'hypertension': 'caution', 'kidney': 'caution'},
        'ingredients': [   ('Yam', '1 portion', 'vegetables', 0),
                           ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0)],
        'steps': ['Pounded yam made from fresh white yam.', "Benue is Nigeria's yam capital."]},
    {   'slug': 'asaro',
        'name': 'Asaro',
        'local_name': 'Yam Pottage',
        'description': 'Soft yam porridge cooked with palm oil, crayfish, peppers and onions',
        'meal_type': 'lunch',
        'image': '/static/recipe-images/boiled-rice-and-beans-with-sauce.jpg',
        'portion': '1 serving',
        'reason': 'Soft yam porridge cooked with palm oil, crayfish, peppers and onions',
        'prep': 20,
        'cook': 35,
        'servings': 1,
        'calories': 300,
        'protein': 8,
        'carbs': 54,
        'fat': 6,
        'sodium_mg': 60,
        'potassium_mg': 280,
        'region': 'north-central',
        'ethnic_origin': 'Igala / Yoruba',
        'condition_safety': {},
        'ingredients': [   ('Palm Oil', '1 portion', 'essentials', 0),
                           ('Crayfish', '1 portion', 'essentials', 0),
                           ('Yam', '1 portion', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0)],
        'steps': [   'Soft yam porridge cooked with palm oil, crayfish, peppers and onions.',
                     'Serve warm.']},
    {   'slug': 'gbegiri',
        'name': 'Gbegiri',
        'local_name': 'Bean Soup',
        'description': 'Bean soup (black-eyed peas or honey beans) cooked until soft',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/vegetable-soup.jpg',
        'portion': '1 serving',
        'reason': 'Bean soup (black-eyed peas or honey beans) cooked until soft',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 200,
        'protein': 15,
        'carbs': 10,
        'fat': 11,
        'sodium_mg': 480,
        'potassium_mg': 520,
        'region': 'north-central',
        'ethnic_origin': 'Yoruba / Kwara',
        'condition_safety': {},
        'ingredients': [   ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0),
                           ('Smoked fish', '1 portion', 'proteins', 0)],
        'steps': ['Bean soup (black-eyed peas or honey beans) cooked until soft.', 'Serve warm.']},
    {   'slug': 'amala',
        'name': 'Amala',
        'local_name': 'Yam Flour Swallow',
        'description': 'Dark swallow made from dried yam flour or unripe plantain flour',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/amala-and-vegetable-soup.jpg',
        'portion': '1 serving',
        'reason': 'Dark swallow made from dried yam flour or unripe plantain flour',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 352,
        'protein': 9,
        'carbs': 63,
        'fat': 7,
        'sodium_mg': 60,
        'potassium_mg': 280,
        'region': 'south-west',
        'ethnic_origin': 'Yoruba',
        'condition_safety': {'diabetes': 'caution'},
        'ingredients': [   ('Yam Flour', '1 portion', 'essentials', 0),
                           ('Yam', '1 portion', 'vegetables', 0),
                           ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0)],
        'steps': [   'Dark swallow made from dried yam flour or unripe plantain flour.',
                     'Serve warm.']},
    {   'slug': 'ewedu-soup',
        'name': 'Ewedu Soup',
        'local_name': 'Jute Leaf Soup',
        'description': 'Slimy green soup made from jute leaves; always served with gbegiri',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/bitter-leaf-soup.jpg',
        'portion': '1 serving',
        'reason': 'Slimy green soup made from jute leaves',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 20,
        'protein': 2,
        'carbs': 1,
        'fat': 1,
        'sodium_mg': 480,
        'potassium_mg': 520,
        'region': 'south-west',
        'ethnic_origin': 'Yoruba',
        'condition_safety': {},
        'ingredients': [   ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0),
                           ('Smoked fish', '1 portion', 'proteins', 0)],
        'steps': ['Slimy green soup made from jute leaves.', 'Always served with gbegiri.']},
    {   'slug': 'efo-riro',
        'name': 'Efo Riro',
        'local_name': 'Stir-Fried Vegetable Soup',
        'description': 'Rich spinach/tete stir-fry with assorted meats, smoked fish, palm oil',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/vegetable-soup.jpg',
        'portion': '1 serving',
        'reason': 'Rich spinach/tete stir-fry with assorted meats, smoked fish, palm oil',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 250,
        'protein': 19,
        'carbs': 12,
        'fat': 14,
        'sodium_mg': 480,
        'potassium_mg': 520,
        'region': 'south-west',
        'ethnic_origin': 'Yoruba',
        'condition_safety': {},
        'ingredients': [   ('Palm Oil', '1 portion', 'essentials', 0),
                           ('Spinach', '1 portion', 'vegetables', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0)],
        'steps': [   'Rich spinach/tete stir-fry with assorted meats, smoked fish, palm oil.',
                     'Serve warm.']},
    {   'slug': 'iyan',
        'name': 'Iyan',
        'local_name': 'Pounded Yam',
        'description': 'Freshly pounded white yam; national favourite across all Yoruba states',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/amala-and-vegetable-soup.jpg',
        'portion': '1 serving',
        'reason': 'Freshly pounded white yam',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 400,
        'protein': 10,
        'carbs': 72,
        'fat': 8,
        'sodium_mg': 60,
        'potassium_mg': 280,
        'region': 'south-west',
        'ethnic_origin': 'Yoruba',
        'condition_safety': {'diabetes': 'caution', 'hypertension': 'caution', 'kidney': 'caution'},
        'ingredients': [   ('Yam', '1 portion', 'vegetables', 0),
                           ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0)],
        'steps': ['Freshly pounded white yam.', 'National favourite across all Yoruba states.']},
    {   'slug': 'jollof-rice-yoruba-style',
        'name': 'Jollof Rice (Yoruba style)',
        'local_name': 'Party Jollof',
        'description': 'Tomato and pepper-based one-pot rice; king of Nigerian parties',
        'meal_type': 'lunch',
        'image': '/static/recipe-images/rice-and-vegetable-sauce.jpg',
        'portion': '1 serving',
        'reason': 'Tomato and pepper-based one-pot rice',
        'prep': 20,
        'cook': 35,
        'servings': 1,
        'calories': 868,
        'protein': 22,
        'carbs': 156,
        'fat': 17,
        'sodium_mg': 60,
        'potassium_mg': 280,
        'region': 'south-west',
        'ethnic_origin': 'Yoruba',
        'condition_safety': {'weight': 'avoid'},
        'ingredients': [   ('Onion', '1 medium', 'vegetables', 0),
                           ('Tomato', '2 medium', 'vegetables', 0),
                           ('Vegetable oil', '1 tbsp', 'essentials', 0)],
        'steps': ['Tomato and pepper-based one-pot rice.', 'King of Nigerian parties.']},
    {   'slug': 'eba-garri',
        'name': 'Eba / Garri',
        'local_name': 'Cassava Swallow',
        'description': "Garri mixed with boiling water; Nigeria's most consumed swallow",
        'meal_type': 'dinner',
        'image': '/static/recipe-images/garri-with-milk-and-groundnut.jpg',
        'portion': '1 serving',
        'reason': 'Garri mixed with boiling water',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 360,
        'protein': 9,
        'carbs': 65,
        'fat': 7,
        'sodium_mg': 60,
        'potassium_mg': 280,
        'region': 'south-west',
        'ethnic_origin': 'Yoruba / Nationwide',
        'condition_safety': {'diabetes': 'caution', 'hypertension': 'caution'},
        'ingredients': [   ('Garri', '1 portion', 'grains', 0),
                           ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0)],
        'steps': ['Garri mixed with boiling water.', "Nigeria's most consumed swallow."]},
    {   'slug': 'ofada-rice-ayamase',
        'name': 'Ofada Rice + Ayamase',
        'local_name': 'Local Rice + Green Stew',
        'description': 'Aromatic local unpolished rice served with spicy green pepper stew',
        'meal_type': 'lunch',
        'image': '/static/recipe-images/ofada-sauce.jpg',
        'portion': '1 serving',
        'reason': 'Aromatic local unpolished rice served with spicy green pepper stew',
        'prep': 20,
        'cook': 35,
        'servings': 1,
        'calories': 500,
        'protein': 12,
        'carbs': 90,
        'fat': 10,
        'sodium_mg': 60,
        'potassium_mg': 280,
        'region': 'south-west',
        'ethnic_origin': 'Yoruba / Ogun',
        'condition_safety': {'weight': 'caution'},
        'ingredients': [   ('Green Pepper', '1 portion', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0),
                           ('Tomato', '2 medium', 'vegetables', 0),
                           ('Vegetable oil', '1 tbsp', 'essentials', 0)],
        'steps': [   'Aromatic local unpolished rice served with spicy green pepper stew.',
                     'Serve warm.']},
    {   'slug': 'ikokore',
        'name': 'Ikokore',
        'local_name': 'Water Yam Pottage',
        'description': 'Grated water yam cooked into a thick pottage with fish and palm oil',
        'meal_type': 'lunch',
        'image': '/static/recipe-images/boiled-rice-and-beans-with-sauce.jpg',
        'portion': '1 serving',
        'reason': 'Grated water yam cooked into a thick pottage with fish and palm oil',
        'prep': 20,
        'cook': 35,
        'servings': 1,
        'calories': 350,
        'protein': 9,
        'carbs': 63,
        'fat': 7,
        'sodium_mg': 60,
        'potassium_mg': 280,
        'region': 'south-west',
        'ethnic_origin': 'Ijebu-Yoruba',
        'condition_safety': {},
        'ingredients': [   ('Palm Oil', '1 portion', 'essentials', 0),
                           ('Yam', '1 portion', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0),
                           ('Tomato', '2 medium', 'vegetables', 0)],
        'steps': [   'Grated water yam cooked into a thick pottage with fish and palm oil.',
                     'Serve warm.']},
    {   'slug': 'ojojo',
        'name': 'Ojojo',
        'local_name': 'Fried Water Yam Fritters',
        'description': 'Grated water yam fried into crispy fritters; breakfast favourite',
        'meal_type': 'snack',
        'image': '/static/recipe-images/puff-puff.jpg',
        'portion': '1 serving',
        'reason': 'Grated water yam fried into crispy fritters',
        'prep': 15,
        'cook': 20,
        'servings': 1,
        'calories': 180,
        'protein': 16,
        'carbs': 4,
        'fat': 11,
        'sodium_mg': 520,
        'potassium_mg': 360,
        'region': 'south-west',
        'ethnic_origin': 'Yoruba',
        'condition_safety': {},
        'ingredients': [   ('Yam', '1 portion', 'vegetables', 0),
                           ('Groundnut oil', 'for frying', 'essentials', 0),
                           ('Salt', 'a pinch', 'essentials', 0)],
        'steps': ['Grated water yam fried into crispy fritters.', 'Breakfast favourite.']},
    {   'slug': 'moin-moin',
        'name': 'Moin Moin',
        'local_name': 'Steamed Bean Pudding',
        'description': 'Steamed bean cake with egg and/or fish inside; served at parties',
        'meal_type': 'snack',
        'image': '/static/recipe-images/puff-puff.jpg',
        'portion': '1 serving',
        'reason': 'Steamed bean cake with egg and/or fish inside',
        'prep': 15,
        'cook': 20,
        'servings': 1,
        'calories': 256,
        'protein': 12,
        'carbs': 35,
        'fat': 8,
        'sodium_mg': 200,
        'potassium_mg': 320,
        'region': 'south-west',
        'ethnic_origin': 'Yoruba',
        'condition_safety': {},
        'ingredients': [   ('Groundnut oil', 'for frying', 'essentials', 0),
                           ('Salt', 'a pinch', 'essentials', 0)],
        'steps': ['Steamed bean cake with egg and/or fish inside.', 'Served at parties.']},
    {   'slug': 'akara',
        'name': 'Akara',
        'local_name': 'Bean Cake / Fritters',
        'description': 'Deep-fried bean fritters; common street food breakfast',
        'meal_type': 'breakfast',
        'image': '/static/recipe-images/akara-and-bread.jpg',
        'portion': '1 serving',
        'reason': 'Deep-fried bean fritters',
        'prep': 15,
        'cook': 20,
        'servings': 1,
        'calories': 71,
        'protein': 3,
        'carbs': 10,
        'fat': 2,
        'sodium_mg': 200,
        'potassium_mg': 320,
        'region': 'south-west',
        'ethnic_origin': 'Yoruba',
        'condition_safety': {},
        'ingredients': [   ('Groundnut', '1 handful', 'proteins', 0),
                           ('Milk', 'to taste', 'essentials', 0)],
        'steps': ['Deep-fried bean fritters.', 'Common street food breakfast.']},
    {   'slug': 'ogi-akamu-pap',
        'name': 'Ogi / Akamu / Pap',
        'local_name': 'Cornmeal Porridge',
        'description': 'Fermented cornmeal porridge; often paired with akara or moi moi',
        'meal_type': 'breakfast',
        'image': '/static/recipe-images/pap-and-milk.jpg',
        'portion': '1 serving',
        'reason': 'Fermented cornmeal porridge',
        'prep': 15,
        'cook': 20,
        'servings': 1,
        'calories': 91,
        'protein': 4,
        'carbs': 13,
        'fat': 3,
        'sodium_mg': 200,
        'potassium_mg': 320,
        'region': 'south-west',
        'ethnic_origin': 'Yoruba',
        'condition_safety': {},
        'ingredients': [   ('Groundnut', '1 handful', 'proteins', 0),
                           ('Milk', 'to taste', 'essentials', 0)],
        'steps': ['Fermented cornmeal porridge.', 'Often paired with akara or moi moi.']},
    {   'slug': 'boli',
        'name': 'Boli',
        'local_name': 'Roasted Plantain',
        'description': 'Charcoal-roasted plantain; served with groundnut or palm oil sauce',
        'meal_type': 'snack',
        'image': '/static/recipe-images/bole-and-fish.jpg',
        'portion': '1 serving',
        'reason': 'Charcoal-roasted plantain',
        'prep': 15,
        'cook': 20,
        'servings': 1,
        'calories': 218,
        'protein': 19,
        'carbs': 5,
        'fat': 13,
        'sodium_mg': 520,
        'potassium_mg': 360,
        'region': 'south-west',
        'ethnic_origin': 'Yoruba',
        'condition_safety': {},
        'ingredients': [   ('Palm Oil', '1 portion', 'essentials', 0),
                           ('Groundnut oil', 'for frying', 'essentials', 0),
                           ('Salt', 'a pinch', 'essentials', 0)],
        'steps': ['Charcoal-roasted plantain.', 'Served with groundnut or palm oil sauce.']},
    {   'slug': 'obe-ata-dindin',
        'name': 'Obe Ata Dindin',
        'local_name': 'Nigerian Tomato Stew',
        'description': 'Fried tomato, onion and pepper stew base; foundation of Nigerian cooking',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/cucumber-tomato-avocado-salad.jpg',
        'portion': '1 serving',
        'reason': 'Fried tomato, onion and pepper stew base',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 293,
        'protein': 22,
        'carbs': 15,
        'fat': 16,
        'sodium_mg': 480,
        'potassium_mg': 520,
        'region': 'south-west',
        'ethnic_origin': 'Yoruba',
        'condition_safety': {},
        'ingredients': [   ('Onion', '1 portion', 'vegetables', 0),
                           ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Smoked fish', '1 portion', 'proteins', 0)],
        'steps': ['Fried tomato, onion and pepper stew base.', 'Foundation of Nigerian cooking.']},
    {   'slug': 'egusi-soup-sw',
        'name': 'Egusi Soup (SW)',
        'local_name': 'Melon Seed Soup',
        'description': 'Ground egusi seeds cooked in palm oil with leafy veg and assorted meats',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/vegetable-soup.jpg',
        'portion': '1 serving',
        'reason': 'Ground egusi seeds cooked in palm oil with leafy veg and assorted meats',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 700,
        'protein': 52,
        'carbs': 35,
        'fat': 39,
        'sodium_mg': 480,
        'potassium_mg': 520,
        'region': 'south-west',
        'ethnic_origin': 'Yoruba',
        'condition_safety': {'weight': 'avoid'},
        'ingredients': [   ('Palm Oil', '1 portion', 'essentials', 0),
                           ('Egusi', '1 portion', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0)],
        'steps': [   'Ground egusi seeds cooked in palm oil with leafy veg and assorted meats.',
                     'Serve warm.']},
    {   'slug': 'semo-semovita',
        'name': 'Semo / Semovita',
        'local_name': 'Wheat Semolina Swallow',
        'description': 'Semolina-based smooth swallow; popular urban alternative to pounded yam',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/vegetable-soup.jpg',
        'portion': '1 serving',
        'reason': 'Semolina-based smooth swallow',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 600,
        'protein': 15,
        'carbs': 108,
        'fat': 12,
        'sodium_mg': 60,
        'potassium_mg': 280,
        'region': 'south-west',
        'ethnic_origin': 'Yoruba / Nationwide',
        'condition_safety': {'diabetes': 'caution', 'weight': 'caution'},
        'ingredients': [   ('Yam', '1 portion', 'vegetables', 0),
                           ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0)],
        'steps': ['Semolina-based smooth swallow.', 'Popular urban alternative to pounded yam.']},
    {   'slug': 'adalu',
        'name': 'Adalu',
        'local_name': 'Beans and Corn Porridge',
        'description': 'Beans and corn cooked together into a hearty one-pot meal',
        'meal_type': 'lunch',
        'image': '/static/recipe-images/beans-and-bread-lover.jpg',
        'portion': '1 serving',
        'reason': 'Beans and corn cooked together into a hearty one-pot meal',
        'prep': 20,
        'cook': 35,
        'servings': 1,
        'calories': 400,
        'protein': 10,
        'carbs': 72,
        'fat': 8,
        'sodium_mg': 60,
        'potassium_mg': 280,
        'region': 'south-west',
        'ethnic_origin': 'Yoruba',
        'condition_safety': {},
        'ingredients': [   ('Onion', '1 medium', 'vegetables', 0),
                           ('Tomato', '2 medium', 'vegetables', 0),
                           ('Vegetable oil', '1 tbsp', 'essentials', 0)],
        'steps': ['Beans and corn cooked together into a hearty one-pot meal.', 'Serve warm.']},
    {   'slug': 'isu-didan-yam-porridge',
        'name': 'Isu Didan (Yam porridge)',
        'local_name': 'Yam Pepper Soup',
        'description': 'Spicy yam pepper soup; distinct Ekiti preparation',
        'meal_type': 'lunch',
        'image': '/static/recipe-images/boiled-rice-and-beans-with-sauce.jpg',
        'portion': '1 serving',
        'reason': 'Spicy yam pepper soup',
        'prep': 20,
        'cook': 35,
        'servings': 1,
        'calories': 300,
        'protein': 8,
        'carbs': 54,
        'fat': 6,
        'sodium_mg': 60,
        'potassium_mg': 280,
        'region': 'south-west',
        'ethnic_origin': 'Yoruba',
        'condition_safety': {},
        'ingredients': [   ('Yam', '1 portion', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0),
                           ('Tomato', '2 medium', 'vegetables', 0),
                           ('Vegetable oil', '1 tbsp', 'essentials', 0)],
        'steps': ['Spicy yam pepper soup.', 'Distinct Ekiti preparation.']},
    {   'slug': 'okra-soup-ilasepo',
        'name': 'Okra Soup (Ilasepo)',
        'local_name': 'Draw Okra',
        'description': 'Okra cooked with assorted seafood and meats; slimy draw soup',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/seafood-okra-soup.jpg',
        'portion': '1 serving',
        'reason': 'Okra cooked with assorted seafood and meats',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 120,
        'protein': 9,
        'carbs': 6,
        'fat': 7,
        'sodium_mg': 480,
        'potassium_mg': 520,
        'region': 'south-west',
        'ethnic_origin': 'Yoruba',
        'condition_safety': {},
        'ingredients': [   ('Okra', '1 portion', 'vegetables', 0),
                           ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0)],
        'steps': ['Okra cooked with assorted seafood and meats.', 'Slimy draw soup.']},
    {   'slug': 'ewa-agoyin',
        'name': 'Ewa Agoyin',
        'local_name': 'Mashed Beans + Sauce',
        'description': 'Soft mashed beans with spicy onion and dried pepper sauce',
        'meal_type': 'snack',
        'image': '/static/recipe-images/beans-and-bread-lover.jpg',
        'portion': '1 serving',
        'reason': 'Soft mashed beans with spicy onion and dried pepper sauce',
        'prep': 15,
        'cook': 20,
        'servings': 1,
        'calories': 400,
        'protein': 35,
        'carbs': 10,
        'fat': 24,
        'sodium_mg': 520,
        'potassium_mg': 360,
        'region': 'south-west',
        'ethnic_origin': 'Yoruba',
        'condition_safety': {},
        'ingredients': [   ('Onion', '1 portion', 'vegetables', 0),
                           ('Groundnut oil', 'for frying', 'essentials', 0),
                           ('Salt', 'a pinch', 'essentials', 0)],
        'steps': ['Soft mashed beans with spicy onion and dried pepper sauce.', 'Serve warm.']},
    {   'slug': 'pupuru',
        'name': 'Pupuru',
        'local_name': 'Fermented Cassava Swallow',
        'description': 'Fermented cassava flour swallow; distinctive earthy taste; Ondo specialty',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/vegetable-soup.jpg',
        'portion': '1 serving',
        'reason': 'Fermented cassava flour swallow',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 330,
        'protein': 8,
        'carbs': 59,
        'fat': 7,
        'sodium_mg': 60,
        'potassium_mg': 280,
        'region': 'south-west',
        'ethnic_origin': 'Ondo-Yoruba',
        'condition_safety': {'diabetes': 'caution'},
        'ingredients': [   ('Cassava', '1 portion', 'vegetables', 0),
                           ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0)],
        'steps': [   'Fermented cassava flour swallow.',
                     'Distinctive earthy taste.',
                     'Ondo specialty.']},
    {   'slug': 'ofe-onugbu',
        'name': 'Ofe Onugbu',
        'local_name': 'Bitter Leaf Soup',
        'description': 'Rich soup made with chopped bitter leaves, egusi, cocoyam; thickened',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/bitter-leaf-soup.jpg',
        'portion': '1 serving',
        'reason': 'Rich soup made with chopped bitter leaves, egusi, cocoyam',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 400,
        'protein': 30,
        'carbs': 20,
        'fat': 22,
        'sodium_mg': 480,
        'potassium_mg': 520,
        'region': 'south-east',
        'ethnic_origin': 'Igbo',
        'condition_safety': {},
        'ingredients': [   ('Cocoyam', '1 portion', 'vegetables', 0),
                           ('Egusi', '1 portion', 'essentials', 0),
                           ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0)],
        'steps': ['Rich soup made with chopped bitter leaves, egusi, cocoyam.', 'Thickened.']},
    {   'slug': 'ofe-oha',
        'name': 'Ofe Oha',
        'local_name': 'Oha Leaf Soup',
        'description': 'Tender oha (ora) leaves cooked in palm oil with assorted meats; special '
                       'occasion soup',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/bitter-leaf-soup.jpg',
        'portion': '1 serving',
        'reason': 'Tender oha (ora) leaves cooked in palm oil with assorted meats',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 350,
        'protein': 26,
        'carbs': 18,
        'fat': 19,
        'sodium_mg': 480,
        'potassium_mg': 520,
        'region': 'south-east',
        'ethnic_origin': 'Igbo',
        'condition_safety': {},
        'ingredients': [   ('Palm Oil', '1 portion', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0),
                           ('Smoked fish', '1 portion', 'proteins', 0)],
        'steps': [   'Tender oha (ora) leaves cooked in palm oil with assorted meats.',
                     'Special occasion soup.']},
    {   'slug': 'ofe-nsala',
        'name': 'Ofe Nsala',
        'local_name': 'White Soup / Catfish Soup',
        'description': 'Light peppery white soup with catfish; thickened with ground yam; no palm '
                       'oil',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/white-rice-vegetable-soup-and-fried-chicken.jpg',
        'portion': '1 serving',
        'reason': 'Light peppery white soup with catfish',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 250,
        'protein': 19,
        'carbs': 12,
        'fat': 14,
        'sodium_mg': 480,
        'potassium_mg': 520,
        'region': 'south-east',
        'ethnic_origin': 'Igbo',
        'condition_safety': {},
        'ingredients': [   ('Palm Oil', '1 portion', 'essentials', 0),
                           ('Yam', '1 portion', 'vegetables', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0)],
        'steps': [   'Light peppery white soup with catfish.',
                     'Thickened with ground yam.',
                     'No palm oil.']},
    {   'slug': 'egusi-soup-se',
        'name': 'Egusi Soup (SE)',
        'local_name': 'Melon Seed Soup',
        'description': 'Ground egusi fried in palm oil with vegetables and assorted meats',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/vegetable-soup.jpg',
        'portion': '1 serving',
        'reason': 'Ground egusi fried in palm oil with vegetables and assorted meats',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 700,
        'protein': 52,
        'carbs': 35,
        'fat': 39,
        'sodium_mg': 480,
        'potassium_mg': 520,
        'region': 'south-east',
        'ethnic_origin': 'Igbo',
        'condition_safety': {'weight': 'avoid'},
        'ingredients': [   ('Palm Oil', '1 portion', 'essentials', 0),
                           ('Egusi', '1 portion', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0)],
        'steps': [   'Ground egusi fried in palm oil with vegetables and assorted meats.',
                     'Serve warm.']},
    {   'slug': 'ofe-akwu-banga-soup',
        'name': 'Ofe Akwu / Banga Soup',
        'local_name': 'Palm Nut Soup',
        'description': 'Soup made from extracted palm nut juice with assorted meats and seafood',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/vegetable-soup.jpg',
        'portion': '1 serving',
        'reason': 'Soup made from extracted palm nut juice with assorted meats and seafood',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 440,
        'protein': 33,
        'carbs': 22,
        'fat': 24,
        'sodium_mg': 480,
        'potassium_mg': 520,
        'region': 'south-east',
        'ethnic_origin': 'Igbo / Delta',
        'condition_safety': {},
        'ingredients': [   ('Palm Nut', '1 portion', 'essentials', 0),
                           ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0)],
        'steps': [   'Soup made from extracted palm nut juice with assorted meats and seafood.',
                     'Serve warm.']},
    {   'slug': 'ofe-owerri',
        'name': 'Ofe Owerri',
        'local_name': 'Owerri Soup',
        'description': 'Special Imo soup combining oha/achi/cocoyam with assorted meats; delicacy',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/vegetable-soup.jpg',
        'portion': '1 serving',
        'reason': 'Special Imo soup combining oha/achi/cocoyam with assorted meats',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 380,
        'protein': 28,
        'carbs': 19,
        'fat': 21,
        'sodium_mg': 480,
        'potassium_mg': 520,
        'region': 'south-east',
        'ethnic_origin': 'Igbo',
        'condition_safety': {},
        'ingredients': [   ('Cocoyam', '1 portion', 'vegetables', 0),
                           ('Achi', '1 portion', 'essentials', 0),
                           ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0)],
        'steps': ['Special Imo soup combining oha/achi/cocoyam with assorted meats.', 'Delicacy.']},
    {   'slug': 'fufu-akpu',
        'name': 'Fufu / Akpu',
        'local_name': 'Fermented Cassava Fufu',
        'description': 'Fermented cassava swallow; the soul food of Igbo culture',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/vegetable-soup.jpg',
        'portion': '1 serving',
        'reason': 'Fermented cassava swallow',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 330,
        'protein': 8,
        'carbs': 59,
        'fat': 7,
        'sodium_mg': 60,
        'potassium_mg': 280,
        'region': 'south-east',
        'ethnic_origin': 'Igbo',
        'condition_safety': {'diabetes': 'caution'},
        'ingredients': [   ('Cassava', '1 portion', 'vegetables', 0),
                           ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0)],
        'steps': ['Fermented cassava swallow.', 'The soul food of Igbo culture.']},
    {   'slug': 'ji-mmiri-oku',
        'name': 'Ji Mmiri Oku',
        'local_name': 'Yam Pepper Soup',
        'description': 'Boiled yam in hot peppery broth; traditionally served to nursing mothers',
        'meal_type': 'snack',
        'image': '/static/recipe-images/puff-puff.jpg',
        'portion': '1 serving',
        'reason': 'Boiled yam in hot peppery broth',
        'prep': 15,
        'cook': 20,
        'servings': 1,
        'calories': 300,
        'protein': 22,
        'carbs': 15,
        'fat': 17,
        'sodium_mg': 480,
        'potassium_mg': 520,
        'region': 'south-east',
        'ethnic_origin': 'Igbo',
        'condition_safety': {},
        'ingredients': [   ('Yam', '1 portion', 'vegetables', 0),
                           ('Groundnut oil', 'for frying', 'essentials', 0),
                           ('Salt', 'a pinch', 'essentials', 0)],
        'steps': ['Boiled yam in hot peppery broth.', 'Traditionally served to nursing mothers.']},
    {   'slug': 'ukwa',
        'name': 'Ukwa',
        'local_name': 'Breadfruit Porridge',
        'description': 'African breadfruit (ukwa) cooked with corn and spices',
        'meal_type': 'snack',
        'image': '/static/recipe-images/puff-puff.jpg',
        'portion': '1 serving',
        'reason': 'African breadfruit (ukwa) cooked with corn and spices',
        'prep': 15,
        'cook': 20,
        'servings': 1,
        'calories': 290,
        'protein': 7,
        'carbs': 52,
        'fat': 6,
        'sodium_mg': 60,
        'potassium_mg': 280,
        'region': 'south-east',
        'ethnic_origin': 'Igbo',
        'condition_safety': {},
        'ingredients': [   ('Groundnut oil', 'for frying', 'essentials', 0),
                           ('Salt', 'a pinch', 'essentials', 0)],
        'steps': ['African breadfruit (ukwa) cooked with corn and spices.', 'Serve warm.']},
    {   'slug': 'ugba-ukpaka',
        'name': 'Ugba / Ukpaka',
        'local_name': 'African Oil Bean Salad',
        'description': 'Fermented oil bean seeds sliced and seasoned with oil, crayfish, utazi',
        'meal_type': 'snack',
        'image': '/static/recipe-images/salad.jpg',
        'portion': '1 serving',
        'reason': 'Fermented oil bean seeds sliced and seasoned with oil, crayfish, utazi',
        'prep': 15,
        'cook': 20,
        'servings': 1,
        'calories': 406,
        'protein': 18,
        'carbs': 56,
        'fat': 12,
        'sodium_mg': 200,
        'potassium_mg': 320,
        'region': 'south-east',
        'ethnic_origin': 'Igbo',
        'condition_safety': {'heart': 'avoid', 'cholesterol': 'avoid', 'uric-acid': 'avoid'},
        'ingredients': [   ('Crayfish', '1 portion', 'essentials', 0),
                           ('Groundnut oil', 'for frying', 'essentials', 0),
                           ('Salt', 'a pinch', 'essentials', 0)],
        'steps': [   'Fermented oil bean seeds sliced and seasoned with oil, crayfish, utazi.',
                     'Serve warm.']},
    {   'slug': 'okpa',
        'name': 'Okpa',
        'local_name': 'Bambara Nut Pudding',
        'description': "Steamed bambara nut cake in banana leaves; Enugu's most iconic street food",
        'meal_type': 'snack',
        'image': '/static/recipe-images/puff-puff.jpg',
        'portion': '1 serving',
        'reason': 'Steamed bambara nut cake in banana leaves',
        'prep': 15,
        'cook': 20,
        'servings': 1,
        'calories': 250,
        'protein': 11,
        'carbs': 34,
        'fat': 8,
        'sodium_mg': 200,
        'potassium_mg': 320,
        'region': 'south-east',
        'ethnic_origin': 'Igbo (Enugu)',
        'condition_safety': {},
        'ingredients': [   ('Groundnut oil', 'for frying', 'essentials', 0),
                           ('Salt', 'a pinch', 'essentials', 0)],
        'steps': [   'Steamed bambara nut cake in banana leaves.',
                     "Enugu's most iconic street food."]},
    {   'slug': 'abakaliki-rice',
        'name': 'Abakaliki Rice',
        'local_name': 'Parboiled Local Rice',
        'description': 'Premium locally milled rice grown in Abakaliki; served with stew',
        'meal_type': 'lunch',
        'image': '/static/recipe-images/rice-and-vegetable-sauce.jpg',
        'portion': '1 serving',
        'reason': 'Premium locally milled rice grown in Abakaliki',
        'prep': 20,
        'cook': 35,
        'servings': 1,
        'calories': 205,
        'protein': 5,
        'carbs': 37,
        'fat': 4,
        'sodium_mg': 60,
        'potassium_mg': 280,
        'region': 'south-east',
        'ethnic_origin': 'Igbo (Ebonyi)',
        'condition_safety': {},
        'ingredients': [   ('Onion', '1 medium', 'vegetables', 0),
                           ('Tomato', '2 medium', 'vegetables', 0),
                           ('Vegetable oil', '1 tbsp', 'essentials', 0)],
        'steps': ['Premium locally milled rice grown in Abakaliki.', 'Served with stew.']},
    {   'slug': 'onugbu-soup-with-cocoyam',
        'name': 'Onugbu Soup with Cocoyam',
        'local_name': 'Bitter Leaf + Cocoyam',
        'description': 'Bitter leaf soup thickened with cocoyam paste; Anambra speciality',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/bitter-leaf-soup.jpg',
        'portion': '1 serving',
        'reason': 'Bitter leaf soup thickened with cocoyam paste',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 420,
        'protein': 32,
        'carbs': 21,
        'fat': 23,
        'sodium_mg': 480,
        'potassium_mg': 520,
        'region': 'south-east',
        'ethnic_origin': 'Igbo',
        'condition_safety': {},
        'ingredients': [   ('Bitter Leaf', '1 portion', 'vegetables', 0),
                           ('Cocoyam', '1 portion', 'vegetables', 0),
                           ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0)],
        'steps': ['Bitter leaf soup thickened with cocoyam paste.', 'Anambra speciality.']},
    {   'slug': 'jollof-rice-igbo',
        'name': 'Jollof Rice (Igbo)',
        'local_name': 'Ukpaka Jollof',
        'description': 'Igbo-style jollof rice cooked with ugba (ukpaka) for unique flavour',
        'meal_type': 'lunch',
        'image': '/static/recipe-images/rice-and-vegetable-sauce.jpg',
        'portion': '1 serving',
        'reason': 'Igbo-style jollof rice cooked with ugba (ukpaka) for unique flavour',
        'prep': 20,
        'cook': 35,
        'servings': 1,
        'calories': 868,
        'protein': 22,
        'carbs': 156,
        'fat': 17,
        'sodium_mg': 60,
        'potassium_mg': 280,
        'region': 'south-east',
        'ethnic_origin': 'Igbo',
        'condition_safety': {'weight': 'avoid'},
        'ingredients': [   ('Onion', '1 medium', 'vegetables', 0),
                           ('Tomato', '2 medium', 'vegetables', 0),
                           ('Vegetable oil', '1 tbsp', 'essentials', 0)],
        'steps': [   'Igbo-style jollof rice cooked with ugba (ukpaka) for unique flavour.',
                     'Serve warm.']},
    {   'slug': 'abacha',
        'name': 'Abacha',
        'local_name': 'African Salad / Cassava Salad',
        'description': 'Dried shredded cassava mixed with ugba, garden eggs, crayfish, palm oil',
        'meal_type': 'snack',
        'image': '/static/recipe-images/abacha.jpg',
        'portion': '1 serving',
        'reason': 'Dried shredded cassava mixed with ugba, garden eggs, crayfish, palm oil',
        'prep': 15,
        'cook': 20,
        'servings': 1,
        'calories': 300,
        'protein': 14,
        'carbs': 41,
        'fat': 9,
        'sodium_mg': 200,
        'potassium_mg': 320,
        'region': 'south-east',
        'ethnic_origin': 'Igbo',
        'condition_safety': {'heart': 'avoid', 'cholesterol': 'avoid', 'uric-acid': 'avoid'},
        'ingredients': [   ('Palm Oil', '1 portion', 'essentials', 0),
                           ('Crayfish', '1 portion', 'essentials', 0),
                           ('Cassava', '1 portion', 'vegetables', 0),
                           ('Groundnut oil', 'for frying', 'essentials', 0)],
        'steps': [   'Dried shredded cassava mixed with ugba, garden eggs, crayfish, palm oil.',
                     'Serve warm.']},
    {   'slug': 'banga-soup',
        'name': 'Banga Soup',
        'local_name': 'Palm Nut Soup',
        'description': 'Soup made from extracted palm fruit juice; each ethnic group has a variant',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/vegetable-soup.jpg',
        'portion': '1 serving',
        'reason': 'Soup made from extracted palm fruit juice',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 440,
        'protein': 33,
        'carbs': 22,
        'fat': 24,
        'sodium_mg': 480,
        'potassium_mg': 520,
        'region': 'south-south',
        'ethnic_origin': 'Urhobo / Ijaw / Efik / Edo',
        'condition_safety': {},
        'ingredients': [   ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0),
                           ('Smoked fish', '1 portion', 'proteins', 0)],
        'steps': [   'Soup made from extracted palm fruit juice.',
                     'Each ethnic group has a variant.']},
    {   'slug': 'edikang-ikong-soup',
        'name': 'Edikang Ikong Soup',
        'local_name': 'Vegetable Royalty Soup',
        'description': 'Premium vegetable soup with ugu and waterleaf; assorted meats and seafood; '
                       'served to guests',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/vegetable-soup.jpg',
        'portion': '1 serving',
        'reason': 'Premium vegetable soup with ugu and waterleaf',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 350,
        'protein': 26,
        'carbs': 18,
        'fat': 19,
        'sodium_mg': 480,
        'potassium_mg': 520,
        'region': 'south-south',
        'ethnic_origin': 'Ibibio / Efik',
        'condition_safety': {},
        'ingredients': [   ('Waterleaf', '1 portion', 'vegetables', 0),
                           ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0)],
        'steps': [   'Premium vegetable soup with ugu and waterleaf.',
                     'Assorted meats and seafood.',
                     'Served to guests.']},
    {   'slug': 'afang-soup',
        'name': 'Afang Soup',
        'local_name': 'Wild Spinach Soup',
        'description': 'Made from afang (wild spinach) and waterleaf with seafood and meats',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/vegetable-soup.jpg',
        'portion': '1 serving',
        'reason': 'Made from afang (wild spinach) and waterleaf with seafood and meats',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 300,
        'protein': 22,
        'carbs': 15,
        'fat': 17,
        'sodium_mg': 480,
        'potassium_mg': 520,
        'region': 'south-south',
        'ethnic_origin': 'Efik / Ibibio / Oron',
        'condition_safety': {},
        'ingredients': [   ('Waterleaf', '1 portion', 'vegetables', 0),
                           ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0)],
        'steps': [   'Made from afang (wild spinach) and waterleaf with seafood and meats.',
                     'Serve warm.']},
    {   'slug': 'ekpang-nkukwo',
        'name': 'Ekpang Nkukwo',
        'local_name': 'Cocoyam Pottage',
        'description': 'Grated cocoyam wrapped in leaves; simmered with periwinkles, fish, palm '
                       'oil',
        'meal_type': 'lunch',
        'image': '/static/recipe-images/boiled-rice-and-beans-with-sauce.jpg',
        'portion': '1 serving',
        'reason': 'Grated cocoyam wrapped in leaves',
        'prep': 20,
        'cook': 35,
        'servings': 1,
        'calories': 350,
        'protein': 9,
        'carbs': 63,
        'fat': 7,
        'sodium_mg': 60,
        'potassium_mg': 280,
        'region': 'south-south',
        'ethnic_origin': 'Efik / Ibibio',
        'condition_safety': {},
        'ingredients': [   ('Palm Oil', '1 portion', 'essentials', 0),
                           ('Cocoyam', '1 portion', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0),
                           ('Tomato', '2 medium', 'vegetables', 0)],
        'steps': [   'Grated cocoyam wrapped in leaves.',
                     'Simmered with periwinkles, fish, palm oil.']},
    {   'slug': 'fisherman-s-soup',
        'name': "Fisherman's Soup",
        'local_name': 'Sea Harvest Soup',
        'description': 'Fresh fish and seafood soup with tomatoes, okro or garri as thickener',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/nigerian-fisherman-soup.jpg',
        'portion': '1 serving',
        'reason': 'Fresh fish and seafood soup with tomatoes, okro or garri as thickener',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 200,
        'protein': 15,
        'carbs': 10,
        'fat': 11,
        'sodium_mg': 480,
        'potassium_mg': 520,
        'region': 'south-south',
        'ethnic_origin': 'Ijaw / Riverine communities',
        'condition_safety': {},
        'ingredients': [   ('Tomatoes', '1 portion', 'vegetables', 0),
                           ('Garri', '1 portion', 'grains', 0),
                           ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0)],
        'steps': [   'Fresh fish and seafood soup with tomatoes, okro or garri as thickener.',
                     'Serve warm.']},
    {   'slug': 'abak-atama-soup',
        'name': 'Abak Atama Soup',
        'local_name': 'Palm Nut Atama Soup',
        'description': 'Palm nut soup flavoured with atama leaves; smoked fish, periwinkles, meat',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/vegetable-soup.jpg',
        'portion': '1 serving',
        'reason': 'Palm nut soup flavoured with atama leaves',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 450,
        'protein': 34,
        'carbs': 22,
        'fat': 25,
        'sodium_mg': 480,
        'potassium_mg': 520,
        'region': 'south-south',
        'ethnic_origin': 'Efik / Ibibio',
        'condition_safety': {},
        'ingredients': [   ('Palm Nut', '1 portion', 'essentials', 0),
                           ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0)],
        'steps': ['Palm nut soup flavoured with atama leaves.', 'Smoked fish, periwinkles, meat.']},
    {   'slug': 'afia-efere',
        'name': 'Afia Efere',
        'local_name': 'Efik White Soup',
        'description': 'Light peppery clear soup without palm oil; thickened with ground yam or '
                       'cocoyam',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/white-rice-vegetable-soup-and-fried-chicken.jpg',
        'portion': '1 serving',
        'reason': 'Light peppery clear soup without palm oil',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 250,
        'protein': 19,
        'carbs': 12,
        'fat': 14,
        'sodium_mg': 480,
        'potassium_mg': 520,
        'region': 'south-south',
        'ethnic_origin': 'Efik',
        'condition_safety': {},
        'ingredients': [   ('Palm Oil', '1 portion', 'essentials', 0),
                           ('Cocoyam', '1 portion', 'vegetables', 0),
                           ('Yam', '1 portion', 'vegetables', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0)],
        'steps': [   'Light peppery clear soup without palm oil.',
                     'Thickened with ground yam or cocoyam.']},
    {   'slug': 'onunu',
        'name': 'Onunu',
        'local_name': 'Mashed Yam & Plantain',
        'description': 'Pounded cooked yam mixed with ripe plantain; served with pepper soup',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/fried-plantain-irish-potato-and-egg.jpg',
        'portion': '1 serving',
        'reason': 'Pounded cooked yam mixed with ripe plantain',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 380,
        'protein': 17,
        'carbs': 52,
        'fat': 11,
        'sodium_mg': 200,
        'potassium_mg': 320,
        'region': 'south-south',
        'ethnic_origin': 'Kalabari-Ijaw',
        'condition_safety': {},
        'ingredients': [   ('Yam', '1 portion', 'vegetables', 0),
                           ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0)],
        'steps': ['Pounded cooked yam mixed with ripe plantain.', 'Served with pepper soup.']},
    {   'slug': 'ofe-nsala-rivers',
        'name': 'Ofe Nsala (Rivers)',
        'local_name': 'White Catfish Soup',
        'description': 'Peppery white soup with fresh catfish; Rivers State variant',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/white-rice-vegetable-soup-and-fried-chicken.jpg',
        'portion': '1 serving',
        'reason': 'Peppery white soup with fresh catfish',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 250,
        'protein': 19,
        'carbs': 12,
        'fat': 14,
        'sodium_mg': 480,
        'potassium_mg': 520,
        'region': 'south-south',
        'ethnic_origin': 'Ijaw / Ogoni',
        'condition_safety': {},
        'ingredients': [   ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0),
                           ('Smoked fish', '1 portion', 'proteins', 0)],
        'steps': ['Peppery white soup with fresh catfish.', 'Rivers State variant.']},
    {   'slug': 'delta-peppersoup',
        'name': 'Delta Peppersoup',
        'local_name': 'Delta Catfish Pepper Soup',
        'description': 'Fiery catfish peppersoup with local spices; healing food at celebrations',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/beef-pepper-soup.jpg',
        'portion': '1 serving',
        'reason': 'Fiery catfish peppersoup with local spices',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 180,
        'protein': 14,
        'carbs': 9,
        'fat': 10,
        'sodium_mg': 480,
        'potassium_mg': 520,
        'region': 'south-south',
        'ethnic_origin': 'Urhobo / Ijaw',
        'condition_safety': {},
        'ingredients': [   ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0),
                           ('Smoked fish', '1 portion', 'proteins', 0)],
        'steps': ['Fiery catfish peppersoup with local spices.', 'Healing food at celebrations.']},
    {   'slug': 'owo-soup',
        'name': 'Owo Soup',
        'local_name': 'Urhobo Palm Oil Soup',
        'description': 'Thick palm oil-based soup eaten with starch; a Delta staple',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/vegetable-soup.jpg',
        'portion': '1 serving',
        'reason': 'Thick palm oil-based soup eaten with starch',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 300,
        'protein': 22,
        'carbs': 15,
        'fat': 17,
        'sodium_mg': 480,
        'potassium_mg': 520,
        'region': 'south-south',
        'ethnic_origin': 'Urhobo',
        'condition_safety': {},
        'ingredients': [   ('Palm Oil', '1 portion', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0),
                           ('Smoked fish', '1 portion', 'proteins', 0)],
        'steps': ['Thick palm oil-based soup eaten with starch.', 'A Delta staple.']},
    {   'slug': 'starch',
        'name': 'Starch',
        'local_name': 'Delta Cassava Starch Swallow',
        'description': 'Yellow cassava starch cooked into a firm swallow; eaten with owo soup',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/vegetable-soup.jpg',
        'portion': '1 serving',
        'reason': 'Yellow cassava starch cooked into a firm swallow',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 495,
        'protein': 12,
        'carbs': 89,
        'fat': 10,
        'sodium_mg': 60,
        'potassium_mg': 280,
        'region': 'south-south',
        'ethnic_origin': 'Urhobo / Itsekiri',
        'condition_safety': {'diabetes': 'caution'},
        'ingredients': [   ('Cassava', '1 portion', 'vegetables', 0),
                           ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0)],
        'steps': ['Yellow cassava starch cooked into a firm swallow.', 'Eaten with owo soup.']},
    {   'slug': 'orobbo-soup',
        'name': 'Orobbo Soup',
        'local_name': 'Waterleaf Soup',
        'description': 'Light soup made from fresh water leaves with assorted proteins',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/vegetable-soup.jpg',
        'portion': '1 serving',
        'reason': 'Light soup made from fresh water leaves with assorted proteins',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 150,
        'protein': 11,
        'carbs': 8,
        'fat': 8,
        'sodium_mg': 480,
        'potassium_mg': 520,
        'region': 'south-south',
        'ethnic_origin': 'Edo/Bini',
        'condition_safety': {},
        'ingredients': [   ('Palm oil', '1 tbsp', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0),
                           ('Smoked fish', '1 portion', 'proteins', 0)],
        'steps': [   'Light soup made from fresh water leaves with assorted proteins.',
                     'Serve warm.']},
    {   'slug': 'owo-soup-starch',
        'name': 'Owo Soup + Starch',
        'local_name': 'Classic Delta Combination',
        'description': 'Starch swallow paired with Owo palm oil soup; signature Delta meal',
        'meal_type': 'dinner',
        'image': '/static/recipe-images/vegetable-soup.jpg',
        'portion': '1 serving',
        'reason': 'Starch swallow paired with Owo palm oil soup',
        'prep': 25,
        'cook': 45,
        'servings': 1,
        'calories': 790,
        'protein': 36,
        'carbs': 109,
        'fat': 24,
        'sodium_mg': 200,
        'potassium_mg': 320,
        'region': 'south-south',
        'ethnic_origin': 'Urhobo',
        'condition_safety': {'diabetes': 'caution', 'weight': 'avoid'},
        'ingredients': [   ('Palm Oil', '1 portion', 'essentials', 0),
                           ('Fresh pepper', 'to taste', 'vegetables', 0),
                           ('Onion', '1 medium', 'vegetables', 0),
                           ('Smoked fish', '1 portion', 'proteins', 0)],
        'steps': ['Starch swallow paired with Owo palm oil soup.', 'Signature Delta meal.']},
    {   'slug': 'edo-banga-rice',
        'name': 'Edo Banga Rice',
        'local_name': 'Palm Nut Rice',
        'description': 'Rice cooked in palm nut juice with local spices',
        'meal_type': 'lunch',
        'image': '/static/recipe-images/rice-and-vegetable-sauce.jpg',
        'portion': '1 serving',
        'reason': 'Rice cooked in palm nut juice with local spices',
        'prep': 20,
        'cook': 35,
        'servings': 1,
        'calories': 400,
        'protein': 10,
        'carbs': 72,
        'fat': 8,
        'sodium_mg': 60,
        'potassium_mg': 280,
        'region': 'south-south',
        'ethnic_origin': 'Urhobo / Edo',
        'condition_safety': {},
        'ingredients': [   ('Palm Nut', '1 portion', 'essentials', 0),
                           ('Onion', '1 medium', 'vegetables', 0),
                           ('Tomato', '2 medium', 'vegetables', 0),
                           ('Vegetable oil', '1 tbsp', 'essentials', 0)],
        'steps': ['Rice cooked in palm nut juice with local spices.', 'Serve warm.']},
    {   'slug': 'pepper-soup',
        'name': 'Pepper Soup',
        'local_name': 'Nigerian Pepper Soup',
        'description': 'Clear peppery broth with goat meat / catfish / chicken; medicinal spices',
        'meal_type': 'snack',
        'image': '/static/recipe-images/pepper-soup.jpg',
        'portion': '1 serving',
        'reason': 'Clear peppery broth with goat meat / catfish / chicken',
        'prep': 15,
        'cook': 20,
        'servings': 1,
        'calories': 180,
        'protein': 14,
        'carbs': 9,
        'fat': 10,
        'sodium_mg': 480,
        'potassium_mg': 520,
        'region': 'south-south',
        'ethnic_origin': 'Cross River / Various',
        'condition_safety': {},
        'ingredients': [   ('Groundnut oil', 'for frying', 'essentials', 0),
                           ('Salt', 'a pinch', 'essentials', 0)],
        'steps': ['Clear peppery broth with goat meat / catfish / chicken.', 'Medicinal spices.']}]


def seed_recipes(db: Session) -> None:
    seen_slugs = {spec["slug"] for spec in RECIPES}

    # Drop any previously-seeded recipes that are no longer in the corpus,
    # including rows that reference them (SQLite does not enforce FKs by
    # default, so without this meal plans keep orphaned recipe_ids and the
    # dashboard 500s). Affected users get a fresh plan on next dashboard load.
    stale_recipes = db.scalars(
        select(Recipe).where(Recipe.is_seeded.is_(True), Recipe.slug.notin_(seen_slugs))
    ).all()
    if stale_recipes:
        stale_ids = [r.id for r in stale_recipes]
        db.execute(delete(MealPlanItem).where(MealPlanItem.recipe_id.in_(stale_ids)))
        db.execute(delete(ScanResult).where(ScanResult.recipe_id.in_(stale_ids)))
        for stale in stale_recipes:
            db.delete(stale)

    for spec in RECIPES:
        existing = db.scalar(select(Recipe).where(Recipe.slug == spec["slug"]))
        recipe = existing or Recipe(slug=spec["slug"])
        recipe.name = spec["name"]
        recipe.local_name = spec.get("local_name")
        recipe.description = spec.get("description")
        recipe.meal_type = spec["meal_type"]
        recipe.image_url = spec["image"]
        recipe.prep_minutes = spec["prep"]
        recipe.cook_minutes = spec["cook"]
        recipe.servings = spec["servings"]
        recipe.calories = spec["calories"]
        recipe.protein_g = spec["protein"]
        recipe.carbs_g = spec["carbs"]
        recipe.fat_g = spec["fat"]
        recipe.sodium_mg = spec["sodium_mg"]
        recipe.potassium_mg = spec["potassium_mg"]
        recipe.portion = spec["portion"]
        recipe.reason = spec["reason"]
        recipe.condition_safety = spec["condition_safety"]
        recipe.cuisine_region = spec.get("region")
        recipe.is_seeded = True

        if existing is None:
            db.add(recipe)
            db.flush()

        recipe.ingredients.clear()
        for item, amount, category, naira_kobo in spec["ingredients"]:
            recipe.ingredients.append(
                RecipeIngredient(
                    item=item, amount=amount, category=category,
                    naira_kobo=naira_kobo, sort_order=0,
                )
            )
        recipe.steps.clear()
        for index, instruction in enumerate(spec["steps"], start=1):
            recipe.steps.append(RecipeStep(step_number=index, instruction=instruction))

    db.commit()
